apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash-indexer.fullname" . }}-config
  labels:
    {{- include "logstash-indexer.labels" . | nindent 4 }}
data:
{{- range $name, $content := .Values.logstashConfig }}
  {{ $name }}: |
{{ tpl $content $ | indent 4 }}
{{- end }}
