{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash-indexer.fullname" . }}
  labels:
    {{- include "logstash-indexer.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "logstash-indexer.selectorLabels" . | nindent 4 }}
{{- end }}
